apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "stord-sre-challenge.fullname" . }}-migrate-{{ now | unixEpoch }}
  labels:
    {{- include "stord-sre-challenge.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "0"
    # "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "stord-sre-challenge.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "stord-sre-challenge.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      restartPolicy: Never
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/app/bin/migrate"]
          env:
            - name: PHX_HOST
              value: {{ .Values.application.phx_host }}
            - name: POOL_SIZE
              value: "{{ .Values.application.pool_size }}"
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-database-url
                  key: database_url
            - name: SECRET_KEY_BASE
              valueFrom:
                secretKeyRef:
                  name: challenge-secret-key-base
                  key: secret-key-base
          volumeMounts:
            - name: config
              mountPath: /app/releases/1.0.3/runtime.exs
              subPath: runtime.exs
              readOnly: true
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: config
          configMap:
            name: {{ .Release.Name }}-configmap
            items:
              - key: runtime.exs
                path: runtime.exs
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
