apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-database-url
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-10"
type: Opaque
data:
  database_url: {{ (printf "ecto://%s:%s@%s/%s" .Values.database.user .Values.database.pass .Values.database.host .Values.database.name | b64enc) }}
