apiVersion: v1
kind: Secret
metadata:
  name: challenge-secret-key-base
  annotations:
    "helm.sh/resource-policy": "keep"
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-10"
type: Opaque
data:
  {{- $secretObj := (lookup "v1" "Secret" .Release.Namespace "challenge-secret-key-base") | default dict }}
  {{- $secretData := (get $secretObj "data") | default dict }}
  {{- $secretKeyBase := (get $secretData "secret-key-base") | default (randAlphaNum 64 | b64enc) }}
  secret-key-base: {{ $secretKeyBase | quote }}